export const NAVIGATION_HEIGHT = 60
export const NAVIGATION_HORIZONTAL_MARGIN = 12
export const NAVIGATION_VERTICAL_MARGIN = 16
export const NAVIGATION_RADIUS = 16
export const NAVIGATION_CENTER_BUTTON_SIZE = 60
export const NAVIGATION_CENTER_LENGTH = 150
export const NAVIGATION_CURVE_BOTTOM = 30
export const NAVIGATION_CURVE_STRENGTH = 35
export const NAVIGATION_BUTTON_PADDING = 8
export const MAX_WIDTH = 550
export const NAVIGATION_BUTTON_GAP = -48

export const CENTER_BLOCK_WIDTH =
  NAVIGATION_CENTER_LENGTH - NAVIGATION_CURVE_STRENGTH + NAVIGATION_BUTTON_GAP

export const NAVIGATION_SAFE_AREA =
  NAVIGATION_VERTICAL_MARGIN +
  NAVIGATION_HEIGHT -
  NAVIGATION_CURVE_BOTTOM +
  NAVIGATION_BUTTON_PADDING * 2 +
  NAVIGATION_CENTER_BUTTON_SIZE

// export const DEFAULT_ACTIVE_ACCENT_COLOR = Colors.TEXT.PRIMARY_ACTIVE
// export const DEFAULT_INACTIVE_ACCENT_COLOR = Colors.TEXT.BODY_LIGHT
export const DEFAULT_INACTIVE_ACCENT_COLOR = 'grey'
export const DEFAULT_ACTIVE_ACCENT_COLOR = 'blue'
export const DEFAULT_ACTIVE_BACKGROUND_COLOR = '#6E96F7'
export const HighlightBar = {
  width: 16,
  height: 2,
  r: 1,
  y: NAVIGATION_HEIGHT - 8,
}

export const ANIMATION_SPEED = 2000
